LykkeMarketPlace/Areas/Settings/Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LykkeMarketPlace.Areas.Settings.Controllers
{
    [Authorize]
    public class DialogController : Controller
    {
        [HttpPost]
        public ActionResult Index()
        {
            return View();
        }
    }
}

LykkeMarketPlace/Controllers/MarketPlaceController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Core;
using Core.Finance;
using Core.Traders;
using LykkeMarketPlace.Models;

namespace LykkeMarketPlace.Controllers
{
    [Authorize]
    public class MarketPlaceController : Controller
    {
        private readonly ITradersRepository _tradersRepository;
        private readonly SrvBalanceAccess _srvBalanceAccess;

        public MarketPlaceController(ITradersRepository tradersRepository, SrvBalanceAccess srvBalanceAccess)
        {
            _tradersRepository = tradersRepository;
            _srvBalanceAccess = srvBalanceAccess;
        }

        [HttpPost]
        public async Task<ActionResult> Index()
        {
            var id = this.GetTraderId();
            var viewModel = new MarketPlaceIndexViewModel
            {
                Trader = await _tradersRepository.GetByIdAsync(id),
                CurrencyBalances = await _srvBalanceAccess.GetCurrencyBalances(id)
            };

            return View(viewModel);
        }


        [HttpPost]
        public ActionResult GetAssets(string currency)
        {

            var viewModel = new GetAssetsViewModel
            {
                Currency = currency,
                Instruments = GlobalSettings.GetFinanceInstruments(currency).ToArray()
            };

            return View(viewModel);
        }
    }
}

LykkeMarketPlace/Views/MarketPlace/GetAssets.cshtml
@using LykkeMarketPlace.Strings
@model LykkeMarketPlace.Models.GetAssetsViewModel


<div style="text-align: center; padding: 20px;">
    @foreach (var instr in Model.Instruments)
    {

        var cur = instr.Base == Model.Currency ? instr.Quoting : instr.Base;

        <table style="display: inline-block;">
            <tr>
                <td>
                    <img src="~/Images/bg_box-shadow-left-300.png" class="panel-shdw" style="height: 180px"/>
                </td>
                <td>

                    <div class="asset-panel">
                        <div class="asset-panel-heading">
                            <table style="width: 100%;">
                                <tr>
                                    <td style="text-align: left;">
                                        <div style="margin-top: -12px; margin-bottom: -12px;">

                                            <img src="~/Images/Currencies/@(instr.Base).png" class="asset-icon"/>
                                            <img src="~/Images/Currencies/@(instr.Quoting).png" class="asset-icon" style="margin-left: -20px;"/>
                                        </div>

                                    </td>

                                    <td style="text-align: center;">
                                        <b>@instr.Base/@instr.Quoting</b>
                                    </td>
                                </tr>
                            </table>

                        </div>


                        <table style="width: 100%;">
                            <tr>
                                <td style="width: 50%">

                                    <div style="padding: 10px;">

                                        <div class="input-group">
                                            <span class="input-group-addon">@Model.Currency</span>
                                            <input id="volume@(cur)" type="number" class="form-control" placeholder="@Phrases.Volume">
                                        </div>

                                    </div>
                                    <div class="btn-group">
                                        <button class="btn btn-primary" style="width: 110px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.43);" onclick="lk.marketOrder('@cur', 'sell')">
                                            <div>Sell Market</div>
                                            <div id="bid@(instr.Id)">---</div>

                                        </button>
                                        <button class="btn btn-danger" style="width: 110px; box-shadow: 0 0 5px rgba(0, 0, 0, 0.43);" onclick="lk.marketOrder('@cur', 'buy')">
                                            <div>Buy Market</div>
                                            <div id="ask@(instr.Id)">---</div>
                                        </button>
                                    </div>
                                    <div style="padding: 10px 10px 5px 10px;" class="top-order">
                                        <div class="input-group">
                                            <span class="input-group-btn">
                                                <button class="btn btn-primary" type="button" onclick="lk.limitOrder('@cur', 'sell')">Sell Limit Order</button>
                                            </span>
                                            <input id="slr@(cur)" type="text" class="form-control" placeholder="Rate"/>
                                        </div><!-- /input-group -->
                                    </div>


                                    <div style="padding: 5px 10px 0 10px;">
                                        <div class="input-group">
                                            <input id="blr@(cur)" type="text" class="form-control" placeholder="Rate"/>
                                            <span class="input-group-btn">
                                                <button class="btn btn-danger" type="button" onclick="lk.limitOrder('@cur', 'buy')">Buy Limit Order</button>
                                            </span>
                                        </div><!-- /input-group -->
                                    </div>

                                    <hr/>

                                    <div style="padding: 5px 10px 0 10px;">
                                        <div class="input-group">

                                            <input id="lobid@(cur)" type="text" class="form-control" placeholder="BID"/>
                                            <span class="input-group-btn">
                                                <button class="btn btn-success" type="button" style="border-radius: 0;" onclick="lk.limitOrder('@cur')">Order</button>
                                            </span>
                                            <input id="loask@(cur)" type="text" class="form-control" placeholder="ASK"/>
                                        </div><!-- /input-group -->
                                    </div>
                                </td>
                                <td style="width: 50%">
                                    <div id="orderBook@(instr.Id)" class="order-book">

                                    </div>

                                </td>
                            </tr>
                        </table>




                    </div>

                </td>
                <td>
                    <img src="~/Images/bg_box-shadow-right-300.png" class="panel-shdw" style="height: 180px"/>
                </td>

            </tr>
            <tr>
                <td colspan="3">
                    <img src="~/Images/shadow-in-250.png" class="btn-shadow"/>
                </td>
            </tr>
        </table>
    }
</div>



<script>
    lk.setCurrentCurrency('@Model.Currency');
</script>

LykkeMarketPlace/Views/MarketPlace/Index.cshtml
@model LykkeMarketPlace.Models.MarketPlaceIndexViewModel
@using Core
@using LykkeMarketPlace.Services
@using LykkeMarketPlace.Strings

@{
    Layout = null;
}
@Scripts.Render(BundleConfig.Lk)
<script src="~/Scripts/jquery.signalR-2.2.0.min.js" type="text/javascript"></script>
<script src="~/signalr/hubs"></script>

<div class="sideBar" data-autoheight="0">
    <div class="sideBarLogo">
        <img src="~/Images/logo-white.png"/>
        <span style="font-size: 9px;">Marketplace</span>
    </div>

    @foreach (var cb in Model.CurrencyBalances)
    {
        <div id="mnu@(cb.Id)" class="sideBarItem" onclick="selectAsset('@cb.Id')">
            <table>
                <tr>
                    <td style="width: 62px;">
                        <img class="curIcon" src="~/Images/Currencies/@(cb.Id).png"/>
                    </td>
                    <td class="sideBarDescription">
                        <div><b>@(GlobalSettings.Currencies[cb.Id].Name)</b>
                        </div>
                        <div style="color: white;">@(cb.Id): <span id="amount@(cb.Id)">@cb.Value.MoneyToStr()</span></div>
                    </td>
                </tr>
            </table>
        </div>
    }

    @*<div id="mnuALL" class="sideBarItem"  onclick="selectAsset('ALL')">
        <table>
            <tr>
                <td style="width: 62px;">
                    <img class="curIcon" src="~/Images/Currencies/all.png" />
                </td>
                <td class="sideBarDescription">
                    <div>
                        <b>@Phrases.AllCurrencies</b>
                    </div>
                </td>
            </tr>
        </table>
    </div>*@

    <div class="sideBarItem" onclick="ui.showDialog('@Url.Action("Index","Orders")');">
        <table>
            <tr>
                <td style="width: 62px;">
                    <img class="curIcon" src="~/Images/Orders.png" />
                </td>
                <td class="sideBarDescription">
                    <div>
                        <b>@Phrases.Orders</b>
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <div class="sideBarItem" onclick="ui.showDialog('@Url.Action("Index","Dialog", new {area="Settings"})');">
        <table>
            <tr>
                <td style="width: 62px;">
                    <img class="curIcon" src="~/Images/Settings.png"/>
                </td>
                <td class="sideBarDescription">
                    <div>
                        <b>@Phrases.Settings</b>
                    </div>
                </td>
            </tr>
        </table>
    </div>


    <div class="sideBarItem">
        <a href="@Url.Action("Logout", "Home")" style="color: #c8c8c8; text-decoration: none;">
            <table>
                <tr>
                    <td style="width: 62px;">
                        <img class="curIcon" src="~/Images/logout.png"/>
                    </td>
                    <td class="sideBarDescription">
                        <div>
                            <b>@Phrases.Logout</b>
                        </div>
                        <div style="color: white;">@Model.Trader.Email</div>
                    </td>
                </tr>
            </table>
        </a>
    </div>
</div>
<div id="content">

</div>
<div id="modalBackground" onclick="ui.hideDialog();">
    <table style="width: 100%; height: 100%">
        <tr>
            <td id="modalData">

            </td>
        </tr>
    </table>
</div>


<script>
    var lk = new LkMarket($.connection.lkHub);
    lk.start();

    var currentAsset = undefined;

    function selectAsset(id) {
        if (currentAsset != undefined) {
            $('#mnu' + currentAsset).removeClass('active');
        }

        currentAsset = id;
        requests.doRequest({url:'@Url.Action("GetAssets")', params:{currency:id}, divResult:'#content', showLoading:true});
        $('#mnu' + currentAsset).addClass('active');

    }


</script>