LykkeMarketPlace/Areas/Settings/Controllers/DialogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LykkeMarketPlace.Areas.Settings.Controllers
{
    [Authorize]
    public class DialogController : Controller
    {
        [HttpPost]
        public ActionResult Index()
        {
            return View();
        }
    }
}

LykkeMarketPlace/Areas/Settings/Controllers/MockDepositsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Common;
using Core.Finance;
using LykkeMarketPlace.Areas.Settings.Models;
using LykkeMarketPlace.Controllers;
using LykkeMarketPlace.Hubs;
using LykkeMarketPlace.Strings;

namespace LykkeMarketPlace.Areas.Settings.Controllers
{
    [Authorize]
    public class MockDepositsController : Controller
    {
        private readonly SrvBalanceAccess _srvBalanceAccess;

        public MockDepositsController(SrvBalanceAccess srvBalanceAccess)
        {
            _srvBalanceAccess = srvBalanceAccess;
        }

        [HttpPost]
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> MockDeposit(MockDepositModel model)
        {
            if (string.IsNullOrEmpty(model.Amount))
                return this.JsonFailResult("#amount", Phrases.FieldShouldNotBeEmpty);

            double amount = 0;

            try
            {
                amount = model.Amount.ParseAnyDouble();
            }
            catch (Exception)
            {
                return this.JsonFailResult("#amount", Phrases.InvalidAmountFormat);
            }

            var id = this.GetTraderId();

            await _srvBalanceAccess.ChangeBalance(id, model.Currency, amount);

            await LkHub.RefreshBalance(id);

            return this.JsonHideDialog();
        }
    }
}

LykkeMarketPlace/Areas/Settings/Views/Dialog/Index.cshtml
@using LykkeMarketPlace.Strings
@model dynamic

@{
    Layout = "~/Views/Shared/_LayoutDialog.cshtml";
    ViewBag.Title = Phrases.Settings;
    ViewBag.Width = "600px";

}

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Mock Deposits</a></li>
    @*<li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>*@
</ul>

<div id="settingsContent">
    
</div>


<script>
    
    function showMockDeposits() {
        requests.doRequest({ url: '@Url.Action("Index","MockDeposits")', divResult: '#settingsContent', showLoading:true });    
    }

    showMockDeposits();

</script>